#+TITLE: Initial Log
#+DATE: 2023-07-28T23:02:56-04:00
My initial README log for this project:

* Purpose
This repo it to test deploying a clog app using the deploy library.


* Round  Zero

** Design
main.lisp was derived from clog 15-tutorial code.

The binary build was derived from the instructions at [[https://github.com/Shinmera/deploy]] How To section.

** Summary
The app will be built in my project root directory/boot

** Steps

*** Iniital running version under slime
- (ql:quickload :config-clog)
- (ql:quickload :test-clog)
- (test-clog/main:start)

This procedure opens a clog window and allows the video and audio to be played, as expected.
*** Create deploy binary
- (asdf:make :text-clog)
This failed because of threads running.
*** Make under rlwrap sbcl
The following will run the app under rlwrap sbcl
- (ql:quickload :config-clog)
- (ql:quickload :test-clog)
- (test-clog/main:start)
*** Building then fails
Next I tried to build with (asdf:make :test-clog) this again fails because of running threads
*** Build and run
The following builds an app from a fresh running rlwrap sbcl instance.
- (ql:quickload :config-clog :test-clog)
- (test-clog/main:start)

This builds a runs and browser refreshes work.

*** A build under rlwraap sbcl run but errors in execution
- (ql:quickload :config-clog)
- (asdf:make :test-clog)
At this point sbcl exits.
. bin/test-clog.exe
This errors.
#+begin_quote
$ bin/test-clog.exe
 ==> Performing warm boot.
   -> Runtime directory is C:/Users/zzzap/Documents/Code/source-projects/ACTIVE/test-clog-deploy/bin/
   -> Resource directory is C:/Users/zzzap/Documents/Code/source-projects/ACTIVE/test-clog-deploy/bin/
 ==> Running boot hooks.
 ==> Reloading foreign libraries.
   -> Loading foreign library #<LIBRARY SQLITE3-LIB>.
   -> Loading foreign library #<LIBRARY LIBSSL>.
   -> Loading foreign library #<LIBRARY LIBCRYPTO>.
 ==> Launching application.
 ==> Epilogue.
 ==> Running quit hooks.
Hunchentoot server is started.
Listening on 0.0.0.0:8080.
HTTP listening on    : 0.0.0.0:8080
HTML root            : C:/Users/zzzap/quicklisp/dists/quicklisp/software/clog-20221106-git/./static-files/
Long poll first      : no
Boot function added  : no
Boot html source use : compiled version, when no file
Boot js source use   : compiled version
Boot file for path / : /boot.html
Unable to open browser.

Subprocess with command "explorer \"http://127.0.0.1:8080\""
 exited with error code 1[2023-07-13 10:56:36 [ERROR]] Wake-for-shutdown connect failed: The condition Socket error in "connect": 10049 (The requested address is not valid in its context.) occurred with errno: 0.
Unhandled SB-THREAD:JOIN-THREAD-ERROR in thread #<SB-THREAD:THREAD "clack-handler-hunchentoot" RUNNING
                                                   {10033F91B3}>:
  Joining thread failed: thread #<THREAD "hunchentoot-listener-0.0.0.0:8080" ABORTED
                                   {1003D26113}> did not return normally.

Backtrace for: #<SB-THREAD:THREAD "clack-handler-hunchentoot" RUNNING {10033F91B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-THREAD:JOIN-THREAD-ERROR {10040780E3}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<SB-THREAD:JOIN-THREAD-ERROR {10040780E3}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {2218882B}>)
2: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-THREAD:JOIN-THREAD-ERROR {10040780E3}>)
3: (INVOKE-DEBUGGER #<SB-THREAD:JOIN-THREAD-ERROR {10040780E3}>)
4: (ERROR SB-THREAD:JOIN-THREAD-ERROR :THREAD #<SB-THREAD:THREAD "hunchentoot-listener-0.0.0.0:8080" ABORTED {1003D26113}> :PROBLEM :ABORT)
5: (SB-THREAD:JOIN-THREAD #<SB-THREAD:THREAD "hunchentoot-listener-0.0.0.0:8080" ABORTED {1003D26113}> :DEFAULT NIL :TIMEOUT NIL)
6: ((:METHOD HUNCHENTOOT:SHUTDOWN (HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER)) #<HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER {10038967B3}>) [fast-method]
7: ((:METHOD HUNCHENTOOT:STOP (HUNCHENTOOT:ACCEPTOR)) #<CLACK.HANDLER.HUNCHENTOOT::CLACK-ACCEPTOR (host 0.0.0.0, port 8080)> :SOFT NIL) [fast-method]
8: ((FLET "CLEANUP-FUN-3" :IN CLACK.HANDLER.HUNCHENTOOT:RUN)) [cleanup]
9: (CLACK.HANDLER.HUNCHENTOOT:RUN #<FUNCTION (LAMBDA (LACK.MIDDLEWARE.BACKTRACE::ENV) :IN "C:/Users/zzzap/quicklisp/dists/quicklisp/software/lack-20221106-git/src/middleware/backtrace.lisp") {1002787B9B}> :ALLOW-OTHER-KEYS T :ADDRESS "0.0.0.0" :PORT 8080 :DEBUG T :USE-THREAD T :ADDRESS "0.0.0.0")
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-138" :IN SB-THREAD::RUN))
13: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-131" :IN SB-THREAD::RUN))
15: (SB-THREAD::RUN)
16: ("foreign function: #x14003E385")
17: ("foreign function: #x14000728A")

unhandled condition in --disable-debugger mode, quitting
#+end_quote
** Observations/questions

- The browser startup may be hacky - try it without the browser startup code. This will divide the failure question.

* Next trial
Remove browser startup.
Added :config-clog as depend.
Test in slime.
Need to request 127.0.0.1:8080 from the browser.

Testing during deploy.
quit slime because it is serving requests.
- Browser refresh can't find server.

* Debug
ENSURE NO slime version of the app in running.
That is after the binary build. Quit slime.

Once I did this all binary launches would fail.

* Research

- [[https://lispcookbook.github.io/cl-cookbook/scripting.html#with-sbcl---images-and-executables]]
  Broader discussion about binary deployment in lisp.
- [[https://github.com/rabbibotton/clog/blob/main/source/clog-system.lisp]]
  The CLOG code for client server update link.
- [[https://github.com/Shinmera/deploy]]
  The deploy README.


* Possible Failure Scenerios

- The deploy binary closes the SBCL  process to quickly
  - rlwrap keeps the sbcl process alive and thus it handles requests
  - emacs slime keeps the process alive too.

** Test early quit scenerio
- Once the browser is open go into a (sleep 10) loop
  - This works under slime.
    - The web handler is still running.
  - Works under rlwrap
    - The web handler still runs 
